name: guotation
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # 依存関係をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docxtpl
          # 必要であれば他の依存関係もインストールしてください

      # pythonバージョンの表示
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # 簡単なテストを実行
      - name: Test script execution
        run: |
          python -c "import tkinter; print(tkinter.TkVersion)"
          python -c "from docxtpl import DocxTemplate; print(DocxTemplate)"
